# Generated by Django 4.0.2 on 2022-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
